export const Resultcontent = [
  {
    id: 0,
    rating: "4.5",
    img: "./adombi.jpg",
    title: "Adombi Hostel",
    type: "This hostel is",
    location: "Ayeduase,North Side",
    host: "Stephen Darkwah",
    amenities: "Wifi · Air condition · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "(GHS 7K/year),to (GHS 5k/year)",
    description:
      "White And Violet Colour, ",
  },
  {
    id: 1,
    img: "./paradise.webp",
    rating: "4.0",
    title: " Paradise regained hostel.",
    type: "Paradise is",
    location: "Ayeduase, North-Side",
    host: "Michael Obeng",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from(GHS 8K/year),to (GHS 5k/year)",
    description:
      ". Green Storey-Building Opposite Casa Mara.",
  },
  {
    id: 2,
    img: "./thersah.jpg",
    rating: "4.7",
    title: "St Theresahs Hostel",
    type: "St Theresahs is",
    location: "Ayeduase,north-side",
    host: "Theresah Akomeah",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from (GHS 10K/year),to (GHS 6k/year)",
    description:
      "cream and yellow color building opposite paradise regained.",
  },
  {
    id: 3,
    img: "./p3.jpg",
    rating: "3.7",
    title: "P3 hostel",
    type: "This hostel",
    location: "Ayeduase, North-Side",
    host: "Godwin Boakye Antwi",
    amenities: "Wifi · Washer · iron",
    smalldescription: "two in one, three in one, four in one",
    price: "ranges from (GHS 5K/year),to (GHS 3k/year)",
    description:
      "pink colored hostel Close To Frontline And Opposite Happy Family.",
  },
  {
    id: 4,
    img: "./franco.jpg",
    rating: "3.8",
    title: "Franco Hostel ",
    type: "Franco Hostel is",
    location: "New York",
    host: "Toju",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in on",
    price: "ranges from (GHS 7K/year),to (GHS 5k/year)",
    description:
      "Pink hostel.",
  },
  {
    id: 5,
    img: "./amandah_hostel.jpg",
    rating: "4.55(155)",
    title: "This Hostel  is",
    type: "This hostel is",
    location: "chicago",
    host: "abod micheal",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "2 guests · 1 bedroom · 0 beds · 1 bath",
    price: "ranges from (GHS 6K/year),to (GHS 4k/year)",
    description:
      ".",
  },
  {
    id: 6,
    img: "./Anarosa.jpg",
    rating: "4.2",
    title: "Anarosa hostel",
    type: "This hostel is",
    location: "Kotei",
    host: "Rosemary Annane",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from GHS4000 to GHS7000",
    description:
      "White Hostel"
  },
  {
    id: 7,
    img: "./canam-hall-2.jpg",
    rating: "3.3",
    title: "Cnam-Hall is",
    type: "hotel Room",
    location: "Washignton",
    host: "Abod",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
    price: "$105",
    description:
      "Extra spacious with modern styling, our open layout studio suite features two beds, a lounge area with a small kitchen, flat screen TV, work space and iHome docking station. Can accommodate up to 4 guests Features lowered shelving and lowered door viewers and latches. Accessible bathrooms include bathtubs with handrails.",
  },
  {
    id: 8,
    img: "./frontline.jpg",
    rating: "4.44(444)",
    title: "Two Bedded Suite",
    type: "hotel Room",
    location: "Washignton",
    host: "Abod",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
    price: "$105",
    description:
      "Extra spacious with modern styling, our open layout studio suite features two beds, a lounge area with a small kitchen, flat screen TV, work space and iHome docking station. Can accommodate up to 4 guests Features lowered shelving and lowered door viewers and latches. Accessible bathrooms include bathtubs with handrails.",
  },
  {
    id: 9,
    img: "./hydes.jpg",
    rating: "4.44(444)",
    title: "Two Bedded Suite",
    type: "hotel Room",
    location: "Washignton",
    host: "Abod",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
    price: "$105",
    description:
      "Extra spacious with modern styling, our open layout studio suite features two beds, a lounge area with a small kitchen, flat screen TV, work space and iHome docking station. Can accommodate up to 4 guests Features lowered shelving and lowered door viewers and latches. Accessible bathrooms include bathtubs with handrails.",
  },
  {
  id:10,
    img: "./dr nap.webp",
    rating: "4.44(444)",
    title: "Two Bedded Suite",
    type: "hotel Room",
    location: "Washignton",
    host: "Abod",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
    price: "$105",
    description:
      "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
  },
  {
    id:11,
      img: "./jecado.jpg",
      rating: "4.44(444)",
      title: "Two Bedded Suite",
      type: "hotel Room",
      location: "Washignton",
      host: "Abod",
      amenities: "Wifi · Washer · iron",
      smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
      price: "$105",
      description:
        "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
    },
    {
      id:12,
        img: "./mass-hostel.jpeg",
        rating: "4.44(444)",
        title: "Two Bedded Suite",
        type: "hotel Room",
        location: "Washignton",
        host: "Abod",
        amenities: "Wifi · Washer · iron",
        smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
        price: "$105",
        description:
          "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
      },
      {
        id:13,
          img: "./shep 2.jpg",
          rating: "4.44(444)",
          title: "Two Bedded Suite",
          type: "hotel Room",
          location: "Washignton",
          host: "Abod",
          amenities: "Wifi · Washer · iron",
          smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
          price: "$105",
          description:
            "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
        },
        {
          id:14,
            img: "./no-weapon.jpg",
            rating: "4.44(444)",
            title: "Two Bedded Suite",
            type: "hotel Room",
            location: "Washignton",
            host: "Abod",
            amenities: "Wifi · Washer · iron",
            smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
            price: "$105",
            description:
              "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
          },
          {
            id:15,
              img: "./orange hostel.jpg",
              rating: "4.44(444)",
              title: "Two Bedded Suite",
              type: "hotel Room",
              location: "Washignton",
              host: "Abod",
              amenities: "Wifi · Washer · iron",
              smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
              price: "$105",
              description:
                "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
            }
];

export const Content = [
  {
    id: 0,
    img: "./Adombi.jpg",
    styles: "bigcontents__list1",
    title: "Adombi Hostel",
    price: "GHS 7K/year", 
    description: "Your one stop location to relax and chill in this school year",
  },
  {
    id: 1,
    img: "./paradise.webp",
    styles: "bigcontents__list1",
    title: "Paradise Regained",
    price: "GHS 1K/year",
    description: "You will have a room but we will imprison you, be back by 12am and leave the hostel by 5am.",
  },
  {
    id: 5,
    img: "./thersah.jpg",
    styles: "bigcontents__list",
    title: "St.Theresah",
    price: "GHS 6K/year",
    description:
      "Hell's kitchen is THE center of the entire city. Some of the best",
  },
  {
    id: 3,
    img: "./p3.jpg",
    title: "P3",
    price: "GHS 3K/year",
    description: "Our Texas hotel offers the traditional comforts of home ",
  },
];
