export const Resultcontent = [
  {
    id: 0,
    rating: "5.0 (192)",
    img: "./adombi.jpg",
    title: "Adombi Hostel",
    type: "1 in 1 to 4 in 1 rooms",
    location: "Ayeduase,North Side",
    host: "",
    amenities: "Wifi · Air condition · kitchen",
    price: "GHS 7K/year",
    description:
      "Massive  bedrooms literally SECONDS from Times Square. Comfortable, spacious and well maintained. full size bedrooms, kitchen, living room, ",
  },
  {
    id: 1,
    img: "./paradise.webp",
    rating: "4.75(102)",
    title: " Bedroom.",
    type: "Entire apartment",
    location: "New Jersey",
    host: "Abod",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "4 guests · 2 bedrooms · 0 beds · 1 bath",
    price: "$150",
    description:
      "This modern one bedroom apartment is found in a luxury apartment building, located in the eclectic neighborhood of Chelsea. Must see attractions include The High Line and Chelsea Market. Step outside and get around the city with ease with access to the A, C and E trains, located at the 34th Street and 8th Avenue subway station and the 1, 2 and 3 trains found at the 34th Street and 7th Avenue subway station.",
  },
  {
    id: 2,
    img: "./thersah.jpg",
    rating: "New",
    title: "Furnished luxury rooms!",
    type: "Private room",
    location: "Florida",
    host: "Micheal",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "1 guest · 1 bedroom · 1 bed · 1 shared bath",
    price: "$80",
    description:
      "Rooms in apartment located in luxury building for rent. Seeking primarily young professionals/ students/ interns. Enjoy a beautiful and safe home with a young environment.",
  },
  {
    id: 3,
    img: "./p3.jpg",
    rating: "4.15(35)",
    title: "Luxury King Room & Suit",
    type: "hotel Room",
    location: "New Jersey",
    host: "Abod Mike",
    amenities: "Wifi · Washer · iron",
    smalldescription: "2 guests · 1 bedroom · 1 bed · 1 private bath",
    price: "$92",
    description:
      "Appointed with sleek furniture, our classic rooms offer the traditional comforts of home in one of the most time-honored hotels in Texas. Our ADA rooms provide you with a spacious bathroom that contains a bath tub with grab bars, and multiple room configurations to choose for your stay with up to 270 square feet and a queen sized bed.",
  },
  {
    id: 4,
    img: "./franco.jpg",
    rating: "3.75(162)",
    title: "Midtown One Bedroom ",
    type: "Entire apartment",
    location: "New York",
    host: "Toju",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "3 guests · 1 bedroom · 1 bed · 1 bath",
    price: "$169",
    description:
      "This modern one bedroom apartment is found in a luxury apartment building, located near the lively Theater District. This area is a tourist’s paradise, as it home to areas such as Times Square, Radio City Music Hall and Rockefeller Center. Step outside and get around the city with ease, as the 1 train is easily accessible from the 50th Street and Broadway subway station.",
  },
  {
    id: 5,
    img: "./amandah_hostel.jpg",
    rating: "4.55(155)",
    title: "PT Square Studio",
    type: "Entire apartment",
    location: "chicago",
    host: "abod micheal",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "2 guests · 1 bedroom · 0 beds · 1 bath",
    price: "$80",
    description:
      "Prime Times square location with access to restaurants & bars.",
  },
  {
    id: 6,
    img: "./Anarosa.jpg",
    rating: "4.2",
    title: "Anarosa hostel",
    type: "This hostel is",
    location: "Kotei",
    host: "Rosemary Annane",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from GHS4000 to GHS7000",
    description:
      "White Hostel"
  },
  {
    id: 7,
    img: "./canam-hall-2.jpg",
    rating: "4.44(444)",
    title: "Two Bedded Suite",
    type: "hotel Room",
    location: "Washignton",
    host: "Abod",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
    price: "$105",
    description:
      "Extra spacious with modern styling, our open layout studio suite features two beds, a lounge area with a small kitchen, flat screen TV, work space and iHome docking station. Can accommodate up to 4 guests Features lowered shelving and lowered door viewers and latches. Accessible bathrooms include bathtubs with handrails.",
  },
  {
    id: 8,
    img: "./frontline.jpg",
    rating: "4.44(444)",
    title: "Two Bedded Suite",
    type: "hotel Room",
    location: "Washignton",
    host: "Abod",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
    price: "$105",
    description:
      "Extra spacious with modern styling, our open layout studio suite features two beds, a lounge area with a small kitchen, flat screen TV, work space and iHome docking station. Can accommodate up to 4 guests Features lowered shelving and lowered door viewers and latches. Accessible bathrooms include bathtubs with handrails.",
  },
  {
    id: 9,
    img: "./hydes.jpg",
    rating: "4.44(444)",
    title: "Two Bedded Suite",
    type: "hotel Room",
    location: "Washignton",
    host: "Abod",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
    price: "$105",
    description:
      "Extra spacious with modern styling, our open layout studio suite features two beds, a lounge area with a small kitchen, flat screen TV, work space and iHome docking station. Can accommodate up to 4 guests Features lowered shelving and lowered door viewers and latches. Accessible bathrooms include bathtubs with handrails.",
  },
  {
  id:10,
    img: "./dr nap.webp",
    rating: "4.44(444)",
    title: "Two Bedded Suite",
    type: "hotel Room",
    location: "Washignton",
    host: "Abod",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
    price: "$105",
    description:
      "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
  },
  {
    id:11,
      img: "./jecado.jpg",
      rating: "4.44(444)",
      title: "Two Bedded Suite",
      type: "hotel Room",
      location: "Washignton",
      host: "Abod",
      amenities: "Wifi · Washer · iron",
      smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
      price: "$105",
      description:
        "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
    },
    {
      id:12,
        img: "./mass-hostel.jpeg",
        rating: "4.44(444)",
        title: "Two Bedded Suite",
        type: "hotel Room",
        location: "Washignton",
        host: "Abod",
        amenities: "Wifi · Washer · iron",
        smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
        price: "$105",
        description:
          "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
      },
      {
        id:13,
          img: "./shep 2.jpg",
          rating: "4.44(444)",
          title: "Two Bedded Suite",
          type: "hotel Room",
          location: "Washignton",
          host: "Abod",
          amenities: "Wifi · Washer · iron",
          smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
          price: "$105",
          description:
            "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
        },
        {
          id:14,
            img: "./no-weapon.jpg",
            rating: "4.44(444)",
            title: "Two Bedded Suite",
            type: "hotel Room",
            location: "Washignton",
            host: "Abod",
            amenities: "Wifi · Washer · iron",
            smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
            price: "$105",
            description:
              "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
          },
          {
            id:15,
              img: "./orange hostel.jpg",
              rating: "4.44(444)",
              title: "Two Bedded Suite",
              type: "hotel Room",
              location: "Washignton",
              host: "Abod",
              amenities: "Wifi · Washer · iron",
              smalldescription: "4 guests · 1 bedroom · 2 beds · 1 private bath",
              price: "$105",
              description:
                "Extra spacious with modern styling, our open layout studio suite features two beds, a lou."
            }
];

export const Content = [
  {
    id: 0,
    img: "./Adombi.jpg",
    title: "Adombi Hostel",
    price: "GHS 7K/year", 
    description: "Your one stop location to relax and chill in this school year",
  },
  {
    id: 1,
    img: "./paradise.webp",
    title: "Paradise Regained",
    price: "GHS 1K/year",
    description: "You will have a room but we will imprison you, be back by 12am and leave the hostel by 5am.",
  },
  {
    id: 5,
    img: "./thersah.jpg",
    title: "St.Theresah",
    price: "GHS 6K/year",
    description:
      "Hell's kitchen is THE center of the entire city. Some of the best",
  },
  {
    id: 3,
    img: "./p3.jpg",
    title: "P3",
    price: "GHS 3K/year",
    description: "Our Texas hotel offers the traditional comforts of home ",
  },
];
